---
title: "GitHub, OneDrive, and Records! Oh My!"
author: "Jeffrey W. Hollister"
date: '`r Sys.Date()`'
output:
  html_document:
    theme: readable
    toc: yes
    toc_float: yes
vignette: >
  %\VignetteIndexEntry{GitHub, OneDrive, and Records! Oh My!} 
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown} 
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE, echo=FALSE}
################################################################################
#Load packages
################################################################################
library("epar")
NOT_CRAN <- identical(tolower(Sys.getenv("NOT_CRAN")), "true")
knitr::opts_chunk$set(purl = NOT_CRAN, 
                      eval = NOT_CRAN,
                      fig.width = 4, 
                      fig.height = 4, 
                      tidy = TRUE,
                      dpi = 100)
```

```{r environ, echo=FALSE}
#key <- readRDS("../tests/testthat/key_file.rds")
#Sys.setenv(mapzen_key=key)
```

# Records and GitHub Repos

Stuff

# Options for Records

# Git and OneDrive

# Git Workflow

# Solution